### ISSUE TITLE
warning

### ISSUE THREAD

**Issue by catv1** [BlueAmulet/SourceRTXTweaks#11]
Warning: Not all patches applied successfully

C:\Users\crims\Documents\Java\GarrysMod>python applypatch.py .
Loading bin/win64/engine.dll
Loading bin/win64/shaderapidx9.dll
Loading bin/win64/client.dll

Patching bin/win64/engine.dll
Failed to locate patch for 753cf30f10
Failed to locate patch for 7e5244
Failed to locate patch for 753c498b4204

Patching bin/win64/shaderapidx9.dll
Failed to locate patch for 480f4ec1c7
Failed to locate patch for 4833cce8??c503004881c448
Failed to locate patch for 4883ec084c

Patching bin/win64/client.dll
Failed to locate patch for 4883ec480f1022
Failed to locate patch for 0fb68154

Writing changes to "patched" folder
No patches applied to bin/win64/engine.dll
No patches applied to bin/win64/shaderapidx9.dll
No patches applied to bin/win64/client.dll

Warning: Not all patches applied successfully

C:\Users\crims\Documents\Java\GarrysMod>

there is no garrys mod folder in patches

**Comment by BlueAmulet** [comment]
64-bit gmod patches are not well supported and have known issues, please use the 32-bit version of gmod at the moment
